# Generated by Django 4.1.4 on 2023-01-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_sub_fac_feedback',
            name='facID',
        ),
        migrations.RemoveField(
            model_name='student_sub_fac_feedback',
            name='fac_dept',
        ),
        migrations.RemoveField(
            model_name='student_sub_fac_feedback',
            name='fac_name',
        ),
        migrations.RemoveField(
            model_name='student_sub_fac_feedback',
            name='sub_id',
        ),
        migrations.RemoveField(
            model_name='student_sub_fac_feedback',
            name='sub_name',
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='fac_name1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='fac_name2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='fac_name3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='fac_name4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='fac_name5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='sub_name1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='sub_name2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='sub_name3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='sub_name4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='sub_name5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
