# Generated by Django 4.1.4 on 2023-01-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_remove_student_sub_fac_feedback_facid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_sub_fac_feedback',
            name='feedback',
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='feedback_fac1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='feedback_fac2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='feedback_fac3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='feedback_fac4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='feedback_fac5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
