# Generated by Django 4.1.4 on 2023-02-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_remove_student_sub_fac_feedback_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10)),
                ('f_fac1_field1', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac1_field2', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac1_field3', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac1_field4', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac1_field5', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac1_field6', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac1_field7', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac2_field1', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac2_field2', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac2_field3', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac2_field4', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac2_field5', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac2_field6', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac2_field7', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac3_field1', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac3_field2', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac3_field3', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac3_field4', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac3_field5', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac3_field6', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac3_field7', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac4_field1', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac4_field2', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac4_field3', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac4_field4', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac4_field5', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac4_field6', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac4_field7', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac5_field1', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac5_field2', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac5_field3', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac5_field4', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac5_field5', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac5_field6', models.CharField(blank=True, max_length=50, null=True)),
                ('f_fac5_field7', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
