# Generated by Django 4.1.4 on 2023-02-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_feedback_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback_table',
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac1_field1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac1_field2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac1_field3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac1_field4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac1_field5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac1_field6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac1_field7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac2_field1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac2_field2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac2_field3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac2_field4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac2_field5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac2_field6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac2_field7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac3_field1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac3_field2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac3_field3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac3_field4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac3_field5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac3_field6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac3_field7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac4_field1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac4_field2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac4_field3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac4_field4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac4_field5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac4_field6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac4_field7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac5_field1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac5_field2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac5_field3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac5_field4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac5_field5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac5_field6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_sub_fac_feedback',
            name='f_fac5_field7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
