# Generated by Django 4.1.4 on 2023-03-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0005_delete_feedback_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_sub_fac_feedback',
            name='feedback_fac1',
        ),
        migrations.RemoveField(
            model_name='student_sub_fac_feedback',
            name='feedback_fac2',
        ),
        migrations.RemoveField(
            model_name='student_sub_fac_feedback',
            name='feedback_fac3',
        ),
        migrations.RemoveField(
            model_name='student_sub_fac_feedback',
            name='feedback_fac4',
        ),
        migrations.RemoveField(
            model_name='student_sub_fac_feedback',
            name='feedback_fac5',
        ),
    ]
